# Generated by Django 6.0.2 on 2026-02-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Propriétaire'), ('tenant', 'Locataire'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
